configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/FrancoNeto/kaztor-dev 

jhipster:
    security:
        authentication:
            jwt:
                secret: 15bc56e9ed2746b7805071831b5097cfd9e6db02

# Enable /management/logfile endpoint for all apps
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
